{
 "title": "Host Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "osd_hosts",
    "query": "label_values(ceph_disk_occupation, exported_instance)"
   },
   {
    "name": "mon_hosts",
    "query": "label_values(ceph_mon_metadata, ceph_daemon)"
   },
   {
    "name": "mds_hosts",
    "query": "label_values(ceph_mds_inodes, ceph_daemon)"
   },
   {
    "name": "rgw_hosts",
    "query": "label_values(ceph_rgw_qlen, ceph_daemon)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD Hosts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata))"
    }
   ]
  },
  {
   "title": "AVG CPU Busy",
   "type": "singlestat",
   "description": "Average CPU busy across all hosts (OSD, RGW, MON etc) within the cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(\n  1 - (\n    avg by(dns_name) \n     (cpu_usage_idle{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\", cpu='cpu-total'} / 100)))"
    }
   ]
  },
  {
   "title": "AVG RAM Utilization",
   "type": "singlestat",
   "description": "Average Memory Usage across all hosts in the cluster (excludes buffer/cache usage)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (((mem_total{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}) - (\n  (mem_free{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"})  + \n  (mem_cached{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}) + \n  (mem_buffered{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}) +\n  (mem_slab{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"})\n  )) /\n (mem_total{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\"}))"
    }
   ]
  },
  {
   "title": "Physical IOPS",
   "type": "singlestat",
   "description": "IOPS Load at the device as reported by the OS on all OSD hosts",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ((irate(diskio_reads{dns_name=~\"($osd_hosts|$mds_hosts).*\"}[5m]))  + \n(irate(diskio_writes{dns_name=~\"($osd_hosts|$mds_hosts).*\"}[5m])))"
    }
   ]
  },
  {
   "title": "AVG Disk Utilization",
   "type": "singlestat",
   "description": "Average Disk utilization for all OSD data devices (i.e. excludes journal/WAL)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (label_replace(label_replace((irate(diskio_io_time[5m]) / 10 ), \"device\", \"$1\", \"name\", \"(.+)\"), \"exported_instance\", \"$1\", \"host\", \"(.+)\") *  on(exported_instance, device) group_right(ceph_daemon) label_replace(ceph_disk_occupation{dns_name=~\"($osd_hosts|$mds_hosts).*\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"))"
    }
   ]
  },
  {
   "title": "Network Load",
   "type": "singlestat",
   "description": "Total send/receive network load across all hosts in the ceph cluster",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  irate(net_bytes_recv{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[1m])\n) +\nsum (\n  irate(net_bytes_sent{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Busy - Top 10 Hosts",
   "type": "graph",
   "description": "Show the top 10 busiest hosts by cpu",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,100 * (\n  1 - (\n    avg by(dns_name) \n     (cpu_usage_idle{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\", cpu='cpu-total'} / 100))))",
     "legendFormat": "{{dns_name}}"
    }
   ]
  },
  {
   "title": "Network Load - Top 10 Hosts",
   "type": "graph",
   "description": "Top 10 hosts by network load",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10, (sum by(dns_name) (\n  (\n  irate(net_bytes_recv{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[1m])\n  ) +\n  (\n irate(net_bytes_sent{dns_name=~\"($osd_hosts|$mon_hosts|$mds_hosts|$rgw_hosts).*\",device!=\"lo\"}[1m])\n  ))\n  )\n)",
     "legendFormat": "{{dns_name}}"
    }
   ]
  }
 ]
}