{
 "title": "Host Details",
 "tags": [ "overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "ceph_hosts",
    "label": "Hostname",
    "query": "label_values(node_scrape_collector_success, instance) "
   }
  ]
 },
 "panels": [
  { "title": "$ceph_hosts System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (ceph_daemon) (ceph_osd_metadata{hostname='$ceph_hosts'}))"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Shows the CPU breakdown. When multiple servers are selected, only the first host's cpu data is shown",
   "gridPos": { "h": 10, "w": 6, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "% Utilization" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\", host='$ceph_hosts'}",
     "legendFormat": "user - {{ host }}"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\", host='$ceph_hosts'}",
     "legendFormat": "iowait - {{ host }}"
    },
    {
     "expr": "cpu_usage_nice{cpu=\"cpu-total\", host='$ceph_hosts'}",
     "legendFormat": "nice - {{ host }}"
    },
    {
     "expr": "cpu_usage_softirq{cpu=\"cpu-total\", host='$ceph_hosts'}",
     "legendFormat": "softirq - {{ host }}"
    },
    {
     "expr": "cpu_usage_irq{cpu=\"cpu-total\", host='$ceph_hosts'}",
     "legendFormat": "irq - {{ host }}"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\", host='$ceph_hosts'}",
     "legendFormat": "system - {{ host }}"
    },
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\", host='$ceph_hosts'}",
     "legendFormat": "idle - {{ host }}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "RAM used" }
   ],
   "targets": [
    { "expr": "mem_used{host='$ceph_hosts'}", "legendFormat": "used" },
    { "expr": "mem_free{host='$ceph_hosts'}", "legendFormat": "Free" },
    {
     "expr": "mem_buffered{host='$ceph_hosts'} + mem_cached{host='$ceph_hosts'}",
     "legendFormat": "buffers/cache"
    },
    { "expr": "mem_total{host='$ceph_hosts'}", "legendFormat": "total" }
   ]
  },
  {
   "title": "Network Load",
   "type": "graph",
   "description": "Show the network load (rx,tx) across all interfaces (excluding loopback 'lo')",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (\n  irate(net_bytes_recv{host='$ceph_hosts',device!=\"lo\"}[1m])\n)",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "sum by (device) (\n  irate(net_bytes_sent{host='$ceph_hosts',device!=\"lo\"}[1m])\n)",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Network drop rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "irate(net_drop_in{host='$ceph_hosts'}[1m])",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "irate(net_drop_out{host='$ceph_hosts'}[1m])",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "Raw Capacity",
   "type": "singlestat",
   "description": "Each OSD consists of a Journal/WAL partition and a data partition. The RAW Capacity shown is the sum of the data partitions across all OSDs on the selected OSD hosts.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes and on (ceph_daemon) ceph_disk_occupation{instance=~\"($ceph_hosts)([\\\\.:].*)?\"})"
    }
   ]
  },
  {
   "title": "Network error rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "yaxes": [
    { "format": "pps", "label": "Send (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "irate(net_err_in{host='$ceph_hosts'}[1m])",
     "legendFormat": "{{device}}.rx"
    },
    {
     "expr": "irate(net_err_out{host='$ceph_hosts'}[1m])",
     "legendFormat": "{{device}}.tx"
    }
   ]
  },
  {
   "title": "OSD Disk Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "$ceph_hosts Disk IOPS",
   "type": "graph",
   "description": "For any OSD devices on the host, this chart shows the iops per physical device. Each device is shown by it's name and corresponding OSD id value",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace((irate(diskio_writes{host='$ceph_hosts'}[5m])), \"device\", \"$1\", \"name\", \"(.+)\"), \"exported_instance\", \"$1\", \"host\", \"(.+)\") *  on(exported_instance, device) group_right(ceph_daemon) label_replace(ceph_disk_occupation{exported_instance='$ceph_hosts'}, \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) writes"
    },
    {
     "expr": "label_replace(label_replace((irate(diskio_reads{host='$ceph_hosts'}[5m])), \"device\", \"$1\", \"name\", \"(.+)\"), \"exported_instance\", \"$1\", \"host\", \"(.+)\") *  on(exported_instance, device) group_right(ceph_daemon) label_replace(ceph_disk_occupation{exported_instance='$ceph_hosts'}, \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) reads"
    }
   ]
  },
  {
   "title": "$ceph_hosts Throughput by Disk",
   "type": "graph",
   "description": "For OSD hosts, this chart shows the disk bandwidth (read bytes/sec + write bytes/sec) of the physical OSD device. Each device is shown by device name, and corresponding OSD id",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace((irate(diskio_write_bytes[5m]) / 10 ), \"device\", \"$1\", \"name\", \"(.+)\"), \"exported_instance\", \"$1\", \"host\", \"(.+)\") *  on(exported_instance, device) group_right(ceph_daemon) label_replace(ceph_disk_occupation{exported_instance='$ceph_hosts'}, \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) write"
    },
    {
     "expr": "label_replace(label_replace((irate(diskio_read_bytes[5m]) / 10 ), \"device\", \"$1\", \"name\", \"(.+)\"), \"exported_instance\", \"$1\", \"host\", \"(.+)\") *  on(exported_instance, device) group_right(ceph_daemon) label_replace(ceph_disk_occupation{exported_instance='$ceph_hosts'}, \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
     "legendFormat": "{{device}}({{ceph_daemon}}) read"
    }
   ]
  },
  {
   "title": "$ceph_hosts I/O Queued RQs * RQ time Waiting",
   "type": "graph",
   "description": "For OSD hosts, this chart shows the latency at the physical drive. Each drive is shown by device name, with it's corresponding OSD id",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms", "label": "Weighted I/O time" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace((irate(diskio_weighted_io_time{host='$ceph_hosts'}[5m])), \"device\", \"$1\", \"name\", \"(.+)\"), \"exported_instance\", \"$1\", \"host\", \"(.+)\") *  on(exported_instance, device) group_right(ceph_daemon) label_replace(ceph_disk_occupation{exported_instance='$ceph_hosts'}, \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  },
  {
   "title": "$ceph_hosts I/O Queue existance time",
   "type": "graph",
   "description": "Show disk utilization % (util) of any OSD devices on the host by the physical device name and associated OSD id.",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms", "label": "I/O time" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace((irate(diskio_io_time{host='$ceph_hosts'}[5m])), \"device\", \"$1\", \"name\", \"(.+)\"), \"exported_instance\", \"$1\", \"host\", \"(.+)\") *  on(exported_instance, device) group_right(ceph_daemon) label_replace(ceph_disk_occupation{exported_instance='$ceph_hosts'}, \"device\", \"$1\", \"device\", \"/dev/(.*)\")",
     "legendFormat": "{{device}}({{ceph_daemon}})"
    }
   ]
  }
 ]
}