{
 "title": "RBD Details",
 "description": "Detailed Performance of RBD Images (IOPS/Throughput/Latency)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "Pool", "query": "label_values(pool)" },
   { "name": "Image", "query": "label_values(image)" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ceph_osd_metadata, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rbd_write_ops{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s])",
     "legendFormat": "Write"
    },
    {
     "expr": "irate(ceph_rbd_read_ops{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rbd_write_bytes{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s])",
     "legendFormat": "Write"
    },
    {
     "expr": "irate(ceph_rbd_read_bytes{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rbd_write_latency_sum{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s]) / irate(ceph_rbd_write_latency_count{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s])",
     "legendFormat": "Write"
    },
    {
     "expr": "irate(ceph_rbd_read_latency_sum{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s]) / irate(ceph_rbd_read_latency_count{job=~\"$job\", pool=\"$Pool\", image=\"$Image\"}[30s])",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}